# docs/openapi.yaml

openapi: 3.0.3
info:
  version: 1.0.0
  title: Contacts app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description:
    This is a documentation of contacts app
tags:
  - name: Contacts
    description: Operations about users.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://127.0.0.1:3000
    description: Development server
  - url: https://nodejs-hw-mongodb-8-bq8y.onrender.com/api-docs
    description: Production server
paths:
  /contacts/{id}:
    get:
      $ref: ../src/swagger/path/contacts/id/get.yaml
    patch:
      $ref: ../src/swagger/path/contacts/id/patch.yaml
    delete:
      $ref: ../src/swagger/path/contacts/id/delete.yaml
  /contacts:
    get:
      $ref: ../src/swagger/path/contacts/get.yaml
    post:
      $ref: ../src/swagger/path/contacts/post.yaml
  /auth/register:
    post:
      $ref: ../src/swagger/path/auth/register/post.yaml
  /auth/login:
    post:
      $ref: ../src/swagger/path/auth/login/post.yaml
  /auth/logout:
    post:
      $ref: ../src/swagger/path/auth/logout/post.yaml
  /auth/refresh:
    post:
      $ref: ../src/swagger/path/auth/refresh/post.yaml
  /auth/send-reset-email:
    post:
      $ref: ../src/swagger/path/auth/send-reset-email/post.yaml
  /auth/reset-pwd:
    post:
      $ref: ../src/swagger/path/auth/reset-pwd/post.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
