# docs/openapi.yaml

openapi: 3.0.3
info:
  version: 1.0.0
  title: Contacts app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description:
    This is a documentation of contacts app
tags:
  - name: Contacts
    description: Operations about users.
  # - name: Auth
  #   description: Auth operations.
servers:
  - url: http://http://localhost:3000
    description: Development server
  - url: https://nodejs-hw-mongodb-7-dpn6.onrender.com
    description: Production server
paths:
  /contacts/{id}:
    get:
      $ref: ../src/swagger/path/contacts/id/get.yaml
  /contacts:
    get:
      $ref: ../src/swagger/path/contacts/get.yaml
    post:
      $ref: ../src/swagger/path/contacts/post.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
